extends SceneTree

const Model := preload("res://fakemon_editor_model.gd")

func _init() -> void:
	var root := ProjectSettings.globalize_path("res://../..").simplify_path()
	var model := Model.new(root)
	assert(model.load_all(), model.error)
	assert(not model.species_names().is_empty(), "Existing Fakemon must load.")
	assert(model.select_species("Scorchick"), "Known base Fakemon must be selectable.")
	assert(model.selected_source.ends_with("battle_data.json"), "Base ownership must be preserved.")
	assert(model.bst() == 310, "Scorchick BST must reflect all six existing stat fields.")
	assert(model.egg_groups_for() == ["Bird", "Cosmic"], "Egg groups must come from egg_groups.json.")
	assert(model.move_catalog().has("ignite"), "Move selectors must use runtime move IDs.")
	assert(model.sprite_paths().player.ends_with("Scorchick_Player.png"), "Sprite references must follow runtime art_id conventions.")
	assert(model.select_species("Scorcaw"), "Known evolved Fakemon must be selectable.")
	assert(model.selected_source.ends_with("evolved_fakemon.json"), "Evolved ownership must be preserved.")
	assert(String(model.draft.get("moveset_source")) == "Scorchick", "Shared movesets must expose the runtime relationship.")
	assert(model.select_species("Scorchick") and model.evolution_target_name == "Scorcaw" and model.evolution_level == 20, "Evolution target must be derived from the child-owned runtime fields.")
	var before := model.draft.duplicate(true)
	assert(not model.is_dirty(), "Loading must not dirty or normalize a Fakemon.")
	assert(model.draft == before, "Read-only inspection must not mutate data.")
	assert(model.add_species("EditorNewEvolution", "Scorchick"), "A newly created evolved form must be stored with a selected parent.")
	assert(model.selected_source.ends_with("evolved_fakemon.json") and model.draft["evolves_from"] == "Scorchick" and model.draft["moveset_source"] == "Scorchick", "New evolved forms must immediately expose evolution targeting and shared moveset fields.")
	assert(model.evolved_data.any(func(mon): return mon.get("name") == "EditorNewEvolution"), "New evolved forms must immediately enter the evolution-target catalog.")
	assert(model.add_species("EditorPromotedBase"), "A base-form fixture must be creatable.");var promoted:Dictionary=model.draft;assert(model._promote_evolution_target(promoted,"Moach"), "A base species selected as an evolution target must be promotable.")
	assert(model.evolved_data.has(promoted) and promoted["moveset_source"]=="Moach" and not promoted.has("moves") and not promoted.has("learnset"), "Promotion must make the target share its parent's moveset immediately.")
	assert(model.select_species("Moach"), "The implemented water encounter Fakemon must load.")
	var water_maps:=model.encounter_maps().filter(func(entry):return entry.kind=="water")
	assert(water_maps.any(func(entry):return entry.file=="canopy_route.json"),"Found In must expose runtime water encounter tables.")
	assert(model.encounter_for("canopy_route.json","Moach","water").assigned,"Moach must be shown in Canopy Route water encounters.")
	model.set_encounter("canopy_route.json",true,17,"water")
	assert(model.encounter_for("canopy_route.json","Moach","water").level==17 and model.encounters_dirty(),"Water encounter levels must be independently editable.")
	model.discard_encounters()
	assert(not model.encounters_dirty(),"Discard must restore water encounter edits without writing maps.")
	print("Fakemon Editor model: 22 assertions passed")
	quit()
