extends SceneTree

func _initialize()->void:
	var temp_path:="user://normalized_move_authoring.json";var file:=FileAccess.open(temp_path,FileAccess.WRITE);file.store_string(FileAccess.get_file_as_string("res://data/battle_data.json"));file.close()
	var animation_ids:PackedStringArray=MoveAnimationEditorModel.new().discover_animations()["ids"]
	var model:=MoveCreatorModel.new();assert(model.load_database(temp_path)==OK)
	assert(model.select_move("pounce") and not model.multi_hit_enabled() and not model.scheduled_effect_enabled(),"Simple moves must keep both optional sections disabled.")
	assert(model.create_move("scheduled_authoring_test","Scheduled Authoring Test","Light","Status").is_empty());model.set_multi_hit_enabled(true);model.set_scheduled_effect_enabled(true);assert(model.validation_errors(animation_ids).is_empty(),"New moves must be able to use only runtime-supported defaults.");model.set_multi_hit_enabled(false);model.set_scheduled_effect_enabled(false);assert(not model.selected_move.has("min_hits") and not model.selected_move.has("max_hits") and not model.selected_move.has("scheduled_effect"),"Disabling optional systems must avoid empty serialized configuration.")

	assert(model.select_move("gnaw") and model.multi_hit_enabled());assert(int(model.selected_move["min_hits"])==2 and int(model.selected_move["max_hits"])==5);var gnaw_original:=model.selected_move.duplicate(true)
	model.set_field("min_hits",3);model.set_field("max_hits",4);assert(model.save(animation_ids)==OK);var reload:=MoveCreatorModel.new();reload.load_database(temp_path);reload.select_move("gnaw");assert(int(reload.selected_move["min_hits"])==3 and int(reload.selected_move["max_hits"])==4);assert(reload.selected_move["power"]==gnaw_original["power"] and reload.selected_move["animation_id"]==gnaw_original["animation_id"],"Editing hit range must preserve unrelated gameplay and animation fields.")
	reload.set_multi_hit_enabled(false);assert(not reload.selected_move.has("min_hits") and not reload.selected_move.has("max_hits"));assert(reload.save(animation_ids)==OK,"Disabling Multi-Hit must remove only its canonical fields.")

	assert(model.select_move("seed") and model.scheduled_effect_enabled());var seed_original:=model.selected_move.duplicate(true);var recipe:Dictionary=model.selected_move["scheduled_effect"];assert(recipe["effect_id"]=="seed" and recipe["trigger"]=="end_of_turn" and recipe["owner"]=="target_battler" and recipe["delay_turns"]==1 and recipe["repeat_count"]==3 and recipe["animation_id"]=="seed_heal")
	model.set_scheduled_effect_field("effect_id","seed_variant");model.set_scheduled_effect_field("trigger","start_of_turn");model.set_scheduled_effect_field("owner","user_battler");model.set_scheduled_effect_field("delay_turns",2);model.set_scheduled_effect_field("repeat_count",4);model.set_scheduled_effect_field("animation_id","prayer_heal");assert(model.save(animation_ids)==OK)
	reload.load_database(temp_path);reload.select_move("seed");recipe=reload.selected_move["scheduled_effect"];assert(recipe["effect_id"]=="seed_variant" and recipe["trigger"]=="start_of_turn" and recipe["owner"]=="user_battler" and recipe["delay_turns"]==2 and recipe["repeat_count"]==4);assert(recipe["animation_id"]=="prayer_heal" and reload.selected_move["animation_id"]==seed_original["animation_id"],"Initial and activation animations must remain independent.");assert(reload.selected_move["weather_overrides"]==seed_original["weather_overrides"],"Unknown Seed specialization must survive structured edits.")
	reload.set_scheduled_effect_field("animation_id","missing_activation");assert(" ".join(reload.validation_errors(animation_ids)).contains("activation animation"));reload.set_scheduled_effect_field("animation_id","prayer_heal")

	for move_id in ["prayer","sun_chorus","torment"]:
		assert(reload.select_move(move_id));var before:=reload.selected_move.duplicate(true);assert(reload.save(animation_ids)==OK);var roundtrip:=MoveCreatorModel.new();roundtrip.load_database(temp_path);roundtrip.select_move(move_id);assert(roundtrip.selected_move==before,"%s must survive a no-change structured round trip."%move_id)

	assert(reload.select_move("prayer"));var prayer_before:=reload.selected_move.duplicate(true);reload.set_scheduled_payload_field("amount",0.25);var animation_file_before:=FileAccess.get_file_as_string("res://data/move_animations/prayer_heal.json");assert(reload.save(animation_ids)==OK);assert(FileAccess.get_file_as_string("res://data/move_animations/prayer_heal.json")==animation_file_before,"Gameplay authoring must not rewrite animation definitions.");assert(reload.selected_move["animation_id"]==prayer_before["animation_id"])
	assert(model.effect_ids().has("seed_variant") and model.effect_ids().has("prayer"),"Effect IDs must be discovered from normalized recipes.");assert(model.effect_owners()==PackedStringArray(["user_battler","target_battler","battle"]),"Owners must come from the runtime contract.");assert(model.effect_triggers()==PackedStringArray(["start_of_turn","end_of_turn"]),"Triggers must come from the runtime contract.");assert(model.effect_payload_kinds()==PackedStringArray(["heal","damage","condition","stat_change"]),"Payload kinds must come from the runtime contract.");assert(model.effect_groups().has("after_move_effect"),"Effect groups must be discovered from move data.")
	print("NORMALIZED_MOVE_AUTHORING_TEST_PASSED");quit()
