extends SceneTree

func _initialize() -> void:
	assert(MoveAnimationDefinition.is_valid_animation_id("ignite_burst"))
	assert(MoveAnimationDefinition.is_valid_animation_id("basic_slash2"))
	assert(not MoveAnimationDefinition.is_valid_animation_id("Ignite Burst"))
	assert(not MoveAnimationDefinition.is_valid_animation_id("2ignite"))
	var model := MoveAnimationEditorModel.new()
	var discovery := model.discover_animations()
	assert(discovery["ids"].has("projectile_test") and discovery["ids"].has("physical_test"), "Canonical discovery must find valid authored animations.")
	var discovery_dir := "user://animation_discovery_test"; DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(discovery_dir))
	var malformed := FileAccess.open(discovery_dir + "/malformed.json", FileAccess.WRITE); malformed.store_string("{not json"); malformed.close()
	var fixture := MoveAnimationDefinition.load_file("res://data/move_animations/projectile_test.json"); assert(fixture.save_file(discovery_dir + "/projectile_test.json") == OK)
	var isolated := model.discover_animations(discovery_dir); assert(isolated["ids"].has("projectile_test") and isolated["warnings"].size() == 1, "Malformed files must warn without breaking discovery.")
	var created := MoveAnimationEditorModel.new(); created.document.data["id"] = "newly_discovered"; assert(created.document.save_file(discovery_dir + "/newly_discovered.json") == OK); assert(created.discover_animations(discovery_dir)["ids"].has("newly_discovered"), "New saves must appear on refresh.")
	var loaded := MoveAnimationEditorModel.new(); loaded.load_document(fixture); assert(loaded.document.data["events"].size() == fixture.data["events"].size(), "Selector loading must reconstruct events.")
	var impact := MoveAnimationEditorModel.default_event("impact_sprite")
	assert(impact["position"]["battler"] == "target" and impact["position"]["anchor"] == "origin" and impact["duration"] == 0.3, "Impact defaults must target Target.Origin.")
	assert(impact["instance_id"] == "impact", "New Impact Sprites must expose an addressable instance ID.")
	assert(not impact["is_behind"], "Sprite actions must default to foreground for backwards compatibility.")
	var definition := MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"impact_single_test","duration":0.35,"events":[impact]}); assert(definition.validation_errors().is_empty(), "Impact Sprite must serialize in schema v1.")
	var layer := Node2D.new(); layer.z_index = 20; root.add_child(layer); var overlay := ColorRect.new(); root.add_child(overlay); var user := Control.new(); user.position=Vector2(40,180); user.z_index=10; root.add_child(user); var target := Control.new(); target.position=Vector2(380,40); target.z_index=10; root.add_child(target); var player := MoveAnimationPlayer.new(); root.add_child(player); await process_frame
	var context := MoveAnimationContext.new(); context.user=user;context.target=target;context.user_art_id="Lochirp";context.target_art_id="Flambian";context.user_side="Player";context.target_side="Wild";context.anchor_repository=GeneratedAnchorRepository.new();context.effect_layer=layer;context.background_overlay=overlay
	player.play(definition,context);await create_timer(0.05).timeout;assert(layer.get_child_count()==1 and layer.get_child(0).z_index==20 and layer.z_index>target.z_index,"Impact Sprite must render on the explicit over-battler layer.");await create_timer(0.35).timeout;assert(layer.get_child_count()==0,"Single-image Impact Sprite must clean itself up.")
	var fading_impact:=impact.duplicate(true);fading_impact["duration"]=0.5;var fade_definition:=MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"impact_fade_test","duration":0.5,"events":[fading_impact,{"time":0.1,"type":"fade_sprite","instance_id":"impact","opacity":0.0,"duration":0.1}]});assert(fade_definition.validation_errors().is_empty(),"Fade Sprite must safely reference a live Impact Sprite.");player.play(fade_definition,context);await create_timer(0.05).timeout;assert(layer.get_child_count()==1);await create_timer(0.2).timeout;assert(layer.get_child_count()==0,"Fading an Impact Sprite to zero must remove it.");await create_timer(0.3).timeout
	var unsafe_fade:=MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"impact_unsafe_fade_test","duration":0.5,"events":[impact,{"time":0.2,"type":"fade_sprite","instance_id":"impact","opacity":0.0,"duration":0.25}]});assert(" ".join(unsafe_fade.validation_errors()).contains("extends past"),"A Fade must not silently outlive its Impact Sprite.")
	var legacy_impact:=impact.duplicate(true);legacy_impact.erase("instance_id");legacy_impact["duration"]=1.0;var legacy_definition:=MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"legacy_impact_cancel_test","duration":1.0,"events":[legacy_impact]});assert(legacy_definition.validation_errors().is_empty());player.play(legacy_definition,context);await create_timer(0.05).timeout;assert(layer.get_child_count()==1);player.cancel();await process_frame;assert(layer.get_child_count()==0,"Stopping preview must clean legacy Impact Sprites without instance IDs.")
	impact["is_behind"]=true;var behind_definition:=MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"impact_behind_test","duration":0.35,"events":[impact]});assert(behind_definition.validation_errors().is_empty(),"Is Behind must serialize as valid animation data.");player.play(behind_definition,context);await create_timer(0.05).timeout;var behind_sprite:=layer.get_child(0) as Sprite2D;assert(behind_sprite.z_index==5 and not behind_sprite.z_as_relative and behind_sprite.z_index<target.z_index,"Checked Impact Sprite must render behind the Fakemon.");await create_timer(0.35).timeout;assert(layer.get_child_count()==0,"Behind effects must clean themselves up.");impact["is_behind"]=false
	impact["sprite_sheet"]={"columns":1,"rows":1,"frame_count":1,"fps":12.0,"loop":true};var sheet_definition:=MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"impact_sheet_test","duration":0.35,"events":[impact]});player.play(sheet_definition,context);await create_timer(0.05).timeout;assert(layer.get_child_count()==1 and (layer.get_child(0) as Sprite2D).hframes==1);await create_timer(0.35).timeout;assert(layer.get_child_count()==0,"Sprite-sheet Impact Sprite must clean itself up.")
	var repository:=GeneratedAnchorRepository.new();assert(repository.get_battle_anchor("Lochirp","Player","definitely_missing")==repository.get_battle_anchor("Lochirp","Player","origin"),"Missing requested anchors must resolve to Origin.")
	var warning_model:=MoveAnimationEditorModel.new();var warning_event:=MoveAnimationEditorModel.default_event("impact_sprite");warning_event["position"]={"battler":"user","anchor":"mouth","offset":[0,0]};warning_model.document.data["events"]=[warning_event];var feedback:=warning_model.preview_anchor_warnings(repository,{"user":{"art_id":"Junrift","side":"Player"}});assert(feedback.size()==1 and feedback[0].contains("using origin"),"Fallback must produce useful nonfatal preview feedback.")
	var fallback_path:="user://anchors_without_origin.json";var anchor_file:=FileAccess.open(fallback_path,FileAccess.WRITE);anchor_file.store_string(JSON.stringify({"sprites":{"Synthetic_Player":{"processed_size":[80,60],"anchors":{}}}}));anchor_file.close();var fallback_repository:=GeneratedAnchorRepository.new(fallback_path);assert(fallback_repository.get_battle_anchor("Synthetic","Player","mouth")==Vector2(40,30),"Missing Origin must safely use processed center.")
	await _test_vertical(player,context,user,target,-40.0,-40.0,"vertical");await _test_vertical(player,context,user,target,35.0,35.0,"vertical");await _test_vertical(player,context,user,target,-25.0,-25.0,"baseline")
	var old_fixture:=MoveAnimationDefinition.load_file("res://data/move_animations/status_impact_test.json");assert(old_fixture!=null and old_fixture.validation_errors().is_empty(),"Existing v0.2 events must remain compatible.")
	print("PRE_MIGRATION_FEATURES_TEST_PASSED")
	quit()

func _test_vertical(player:MoveAnimationPlayer,context:MoveAnimationContext,user:Control,target:Control,distance:float,expected_y:float,direction:String)->void:
	var baseline:=user.position;var definition:=MoveAnimationDefinition.from_dictionary({"format_version":1,"id":"vertical_test","duration":0.35,"events":[{"time":0.0,"type":"move_battler","battler":"user","direction":direction,"distance":distance,"duration":0.1}]});assert(definition.validation_errors().is_empty());player.play(definition,context);await create_timer(0.15).timeout;assert(is_equal_approx(user.position.x,baseline.x),"Vertical movement must preserve X.");assert(is_equal_approx(user.position.y,baseline.y+expected_y),"Vertical distance sign must map directly to Godot Y.");await create_timer(0.25).timeout;assert(user.position==baseline and target.position==Vector2(380,40),"Vertical playback must restore baselines without drift.")
